export const pageVeiculos = '/veiculos'
export const pageLogin = '/login'
export const pageFuncionarios = '/funcionarios'
export const pageOficina = '/oficina'
export const pageMinhaPagina = '/mypage'
export const pageHome = '/'